name: Backend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: backend
        run: npm ci

      - name: Run Tests
        working-directory: backend
        run: npm test

      - name: Build Docker Image
        run: docker build -t employee-management-app-backend:ci ./backend

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.3

      - name: Run Trivy Security Scan
        run: trivy image --severity HIGH,CRITICAL --exit-code 1 employee-management-app-backend:ci
